HOST: http://api.glsdashboard.com/

--- GLS Dashboard API v1.7.0 ---
---
All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)

Blueprint controlled through a [github repo](https://github.com/cmcculloh/test-apiary/blob/master/apiary.apib)

[REST Spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)
---


--
Broadcast Statuses
--
Retrieve broadcast statuses
GET /broadcast_statuses
> Content-Type: aplication/json
< 200
< Content-Type: application/json
{ "items": [{
    "id":1,
	"open_issue":false
	"status":"Broadcasting Web Stream - Due to Weather",
	"require_details": true,
	"marker_url": "http://www.google.com"
}] }



--
Issues
--
Retrieve Issues
GET /issues
> Content-Type: aplication/json
{ "resolved": false }
< 200
< Content-Type: application/json
{ "items": [{
	"id":1,
	"created":"Wed Jun 12 2013 11:33:14 GMT-0400 (CDT)",
	"site_id":"1",
	"site_name":"First Church of Christ",
	"broadcast_status_id":1,
	"broadcast_status":"Broadcasting Web Stream - Due to Weather",
	"contact_person":"John Smith",
	"contact_number":"555-555-1212",
}] }

create an issue comment. This is how issues are resolved as well...
POST /issues/{id}/comment
> Content-Type: application/json
{
	"user_id":1,
	"comment": "adsfasdf adsfadsf asdfasdf",
	"resolved":true
}
< 200
< Content-Type: application/json
+++++
< 400
{ "items": [
{ "message": "please check your payload and try again" }
] }


--
Chat
This is subject to change once i start actually implementing chat...

"All Live" field would just contain a comma separated list of all llive location types that would then be broken out into the proper recipients
--
Send a chat message

Create new issue if appropriate based on broadcast status_id (IF INCLUDED)
POST /chats
> Content-Type: application/json
{
	"message": "some text here",
	"userid": 1,
	"recipients": [{'locationType': 1}, {'locationType': 2}, {'locationId': 1}],
	"broadcast_status_id": 1
}
< 204

Retrieve chat messages applicable to user (includes chat sent directly to that user, to user's site and to all in user's site type, etc.). I'm thinking I'll handle pagination on client side
GET /chats?user_id={1}
< 200
< Content-Type: application/json
{
"count": 3,
"items": [
	{"id":1,"msg":"something"}, {"id":2,"msg":"something"}, {"id":3,"msg":"something"}
]}

/*
	{
		"id":3,
		"user_name": "John Doe",
		"message": "Some text here",
		"date": "Wed Jun 13 2013 11:33:14 GMT-0400 (CDT)"
		"recipients": [{'locationType': 1}, {'locationType': 2}, {"site_id":"sadfsasdf", "site_name":"First Church of Christ}],
		"type": "issue",
		"meta_data":{
			"issue_id":1
			"site_id":1,
			"site_name":"First Church of Christ",
			"broadcast_status_id":1,
			"broadcast_status":"Broadcasting Web Stream - Due to Weather",
			"details":"asdf asdf asdf asdf",
			"contact_person":"John Smith",
			"contact_number":"555-555-1212"
		}
	},
	{
		"id":2,
		"user_name": "Jane Doe",
		"message": "This is my chat text",
		"date": "Wed Jun 12 2013 11:33:14 GMT-0400 (CDT)"
		"recipients": [{'locationType': 1}, {'locationType': 2}, {"site_id":"sadfsasdf", "site_name":"First Church of Christ}],
		"type": "chat"
	},
	{
		"id":1,
		"user_name": "Jane Doorknob",
		"message": "This is my chat text right here!!!",
		"date": "Wed Jun 12 2013 10:33:14 GMT-0400 (CDT)"
		"recipients": [{'locationType': 1}, {'locationType': 2}, {"site_id":"sadfsasdf", "site_name":"First Church of Christ}],
		"type": "chat"
	}
	*/

--
Admin Settings
--
Retrieve Settings
GET /settings
> Content-Type: application/json
< 200
< Content-Type: application/json
{ "items": [{
	"logo":"data:image/png;base64,iVBORw0KGgoAAAANS...",
	"welcome_subject":"blah lah blah",
	"welcome_content":"afds asdf aafds asd fasdfasdf"
}] }

Update (200) or Create (201) admin settings
PUT /settings
> Content-Type: application/json
{
	"logo":"data:image/png;base64,iVBORw0KGgoAAAANS...",
	"welcome_subject":"blah lah blah",
	"welcome_content":"afds asdf aafds asd fasdfasdf"
}
< 204


--
Site Types
--
Retrieve Site Types
GET /site_types
> Content-Type: application/json
< 200
< Content-Type: application/json
{ "items": [{
	"id": 1,
	"site_type": "premiere",
	"live_info": "adsf asdf asdf asdfasf asd fasdf asd",
	"delayed_info": "dfas afsddfw fwe w fasasdf asfa sdfawa w"
}] }

Create new site type
POST /site_types
> Content-Type: application/json
{
	"site_type": "premiere",
	"live_info": "adsf asdf asdf asdfasf asd fasdf asd",
	"delayed_info": "dfas afsddfw fwe w fasasdf asfa sdfawa w"
}
< 201
< Content-Type: application/json
{ "items": [
{
	"id": 1,
	"site_type": "premiere",
	"live_info": "adsf asdf asdf asdfasf asd fasdf asd",
	"delayed_info": "dfas afsddfw fwe w fasasdf asfa sdfawa w"
}] }
+++++
< 400
{ "items": [
{ "message": "please check your payload and try again" }
] }

Update (200) or Create (201) a site type
PUT /site_types/{id}
> Content-Type: application/json
{
	"site_type": "premiere",
	"live_info": "adsf asdf asdf asdfasf asd fasdf asd",
	"delayed_info": "dfas afsddfw fwe w fasasdf asfa sdfawa w"
}
< 200
< Content-Type: application/json
{ "items": [
{
	"id": 1,
	"site_type": "premiere",
	"live_info": "adsf asdf asdf asdfasf asd fasdf asd",
	"delayed_info": "dfas afsddfw fwe w fasasdf asfa sdfawa w"
}] }
+++++
< 201
< Content-Type: application/json
{ "items": [ {
	"id": 1,
	"site_type": "premiere",
	"live_info": "adsf asdf asdf asdfasf asd fasdf asd",
	"delayed_info": "dfas afsddfw fwe w fasasdf asfa sdfawa w"
}] }
+++++
< 400
{ "items": [
	{ "message": "please check your payload and try again" }
] }








--
Sites
--
Retrieve Sites
GET /sites
> Content-Type: application/json
< 200
< Content-Type: application/json
{ "items": [
	{
		"id":1,
		"site_id":"sadfsasdf",
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_type": "premiere",
		"site_time":"live",
		"site_status_id":1,
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221",
		"lat": 234234,
		"lon": 324325,
		"markerURL": "http://www.google.com"
	}
] }

Create new site
POST /sites
> Content-Type: application/json
	{
		"site_id":"sadfsasdf",
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_time":"live",
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221"
	}
< 201
< Content-Type: application/json
{ "items": [
	{
		"id":1,
		"site_id":"sadfsasdf",
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_type": "premiere",
		"site_time":"live",
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221"
		"lat": 234234,
		"lon": 324325,
		"markerURL": "http://www.google.com"
	}] }
+++++
< 400
{ "items": [
{ "message": "please check your payload and try again" }
] }

Update (200) or Create (201) a site
PUT /sites/{id}
> Content-Type: application/json
{
	"site_id":"sadfsasdf",
	"site_name":"Willow Creek Community Church",
	"site_type_id":1,
	"site_time":"live",
	"address": "123 N Main Street",
	"city": "Indianapolis",
	"state": "Indiana",
	"zipcode": "46221"
}
< 200
< Content-Type: application/json
{ "items": [
	{
		"id":1,
		"site_id":"sadfsasdf",
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_type": "premiere",
		"site_time":"live",
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221"
		"lat": 234234,
		"lon": 324325,
		"markerURL": "http://www.google.com"
	}] }
+++++
< 201
< Content-Type: application/json
{ "items": [ {
	"id":1,
	"site_id":"sadfsasdf",
	"site_name":"Willow Creek Community Church",
	"site_type_id":1,
	"site_type": "premiere",
	"site_time":"live",
	"address": "123 N Main Street",
	"city": "Indianapolis",
	"state": "Indiana",
	"zipcode": "46221"
	"lat": 234234,
	"lon": 324325,
	"markerURL": "http://www.google.com"
}] }
+++++
< 400
{ "items": [
	{ "message": "please check your payload and try again" }
] }






--
Login
--
login a user
POST /login
> Content-Type: application/json
{ "username":"john@gmail.com", "userpassword": "password" }
< 200
< Content-Type: application/json
{ "items": [
{
	"id":1,
	"username":"jdoe",
	"email":"jdoe@gmail.com",
	"full_name":"John Doe",
	"mobile_phone":"555-555-5555",
	"isAdmin":false,
	"site":{
		"id":1,
		"site_status_id":1,
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_type": "premiere",
		"site_time":"live",
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221"
	},
	"profileUpdatePrompt": false
}
] }
+++++
< 400
{ "items": [
{ "message": "invalid username/password" }
] }

--
Reset Password
--
reset a user's password
GET /reset-password
> Content-Type: application/json
{ "email": "john@gmail.com" }
< 205

--
Users
The following is a section of resources related to users
--
retrieve all users
GET /users
< 200
< Content-Type: application/json
{ "items": [{
	"id":1,
	"username":"jdoe",
	"email":"jdoe@gmail.com",
	"full_name":"John Doe",
	"mobile_phone":"555-555-5555",
	"isAdmin":false,
	"site":{
		"id":1,
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_type": "premiere",
		"site_time":"live",
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221"
	},
	"profileUpdatePrompt": false
}] }

retrieve all users by site (location)
GET /users/site/{site}
< 200
< Content-Type: application/json
{ "items": [{
	"id":1,
	"username":"jdoe",
	"email":"jdoe@gmail.com",
	"full_name":"John Doe",
	"mobile_phone":"555-555-5555",
	"isAdmin":false,
	"site":{
		"id":1,
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_type": "premiere",
		"site_time":"live",
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221"
	},
	"profileUpdatePrompt": false
}] }


retrieve requested user by id
GET /users/{1}
< 200
< Content-Type: application/json
{ "items": [{
	"id":1,
	"username":"jdoe",
	"email":"jdoe@gmail.com",
	"full_name":"John Doe",
	"mobile_phone":"555-555-5555",
	"isAdmin":false,
	"site":{
		"id":1,
		"site_status_id":1,
		"site_name":"Willow Creek Community Church",
		"site_type_id":1,
		"site_type": "premiere",
		"site_time":"live",
		"address": "123 N Main Street",
		"city": "Indianapolis",
		"state": "Indiana",
		"zipcode": "46221"
	},
	"profileUpdatePrompt": false
}] }
+++++
< 400
< Content-Type: application/json
{ "items": [
    { "message": "Please provide a user's id" }
] }

Create new user
POST /users
> Content-Type: application/json
{
	"username":"jdoe",
	"email": "jdoe@gmail.com",
	"full_name":"John Doe",
	"mobile_phone":"555-555-5555",
	"isAdmin": false,
	site_id: 1
}
< 201
< Content-Type: application/json
{ "items": [
    {
	   "id":1,
	   "username":"jdoe",
	   "email":"jdoe@gmail.com",
       "full_name":"John Doe",
       "mobile_phone":"555-555-5555",
	   "isAdmin":false,
		"site":{
			"id":1,
			"site_name":"Willow Creek Community Church",
			"site_type_id":1,
			"site_type": "premiere",
			"site_time":"live",
			"address": "123 N Main Street",
			"city": "Indianapolis",
			"state": "Indiana",
			"zipcode": "46221"
		},
       "profileUpdatePrompt": false
	}] }
+++++
< 400
{ "items": [
{ "message": "please check your payload and try again" }
] }

Update (200) or Create (201) a user
PUT /users/{id}
> Content-Type: application/json
{
	"username":"jdoe",
	"email": "jdoe@gmail.com",
	"password": "password",
	"full_name":"John Doe",
	"mobile_phone":"555-555-5555",
	"isAdmin": false,
	site_id: 1
}
< 200
< Content-Type: application/json
{ "items": [
{
       "id":1,
	   "username":"jdoe",
	   "email":"jdoe@gmail.com",
       "full_name":"John Doe",
       "mobile_phone":"555-555-5555",
	   "isAdmin":false,
		"site":{
			"id":1,
			"site_name":"Willow Creek Community Church",
			"site_type_id":1,
			"site_type": "premiere",
			"site_time":"live",
			"address": "123 N Main Street",
			"city": "Indianapolis",
			"state": "Indiana",
			"zipcode": "46221"
		},
       "profileUpdatePrompt": false
	}] }
+++++
< 201
< Content-Type: application/json
{ "items": [
{
       "id":1,
	   "username":"jdoe",
	   "email":"jdoe@gmail.com",
       "full_name":"John Doe",
       "mobile_phone":"555-555-5555",
	   "isAdmin":false,
		"site":{
			"id":1,
			"site_name":"Willow Creek Community Church",
			"site_type_id":1,
			"site_type": "premiere",
			"site_time":"live",
			"address": "123 N Main Street",
			"city": "Indianapolis",
			"state": "Indiana",
			"zipcode": "46221"
		},
       "profileUpdatePrompt": false
	}] }
+++++
< 400
{ "items": [
{ "message": "please check your payload and try again" }
] }


Delete user by id
DELETE /users/{id}
> Content-Type: application/json
< 204
+++++
< 400
{ "items": [
{ "message": "please provide user's id" }
] }

-- JSON Schema Validations --
GET /broadcast_statuses
{
    "$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Broadcast Statuses Set",
	"type": "array",
	"items": {
		"title": "Broadcast Status",
		"type": "object",
		"properties":{
			"id":{
				"descripton": "unique identifier for broadcast status",
				"type": "number"
			},
			"open_issue":{
				"description": "Whether this status triggers an issue being created",
				"type": "boolean"
			},
			"status":{
				"description": "populates drop-down box for user submitted statuses",
				"type": "string",
				"oneOf": [
					"Broadcasting Satellite Feed - All Systems Go!",
					"Broadcasting Web Stream - Due to Weather",
					"Broadcasting Web Stream - Due to Other",
					"Rental Projector Issue (Premiere Only) - Still Broadcasting",
					"Other",
					"EMERGENCY - Offline",
					"Offline - End of Day"
				]
			},
			"require_details": {
				"type": "boolean"
			},
			"marker_url": {
				"desctiption": "image url (or data)",
				"type": "string"
			}
		}
	},
	"required": ["id", "open_issue", "status", "require_details", "marker_url"]
}

POST /issues/{id}/comment
{
    "$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Comment on an Issue",
	"type": "object",
	"properties": {
		"user_id":{
			"description": "id of user making comment",
			"type": "number"
		},
		"comment": {
			"description": "user entered text",
			"type": "string"
		},
		"resolved": {
			"description": "whether this comment indicates the resolution of the issue",
			"type": "boolean"
		}
	},
	"required": ["user_id", "comment", "resolved"]
}